# Generated by Django 5.1.4 on 2025-01-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=5)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Media',
                'verbose_name_plural': 'User Media',
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
